<?php
/**
 * Created by PhpStorm.
 * User: TT
 * Date: 2017/6/22
 * Time: 11:46
 */
namespace frontend\widgets;
use backend\models\Goods;
use \yii\base\Widget;

class GoodsCategory extends Widget
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
//        $redis = new \Redis();//实例化redis
//        $redis->connect('127.0.0.1');//连接redis
//        $res_html = $redis->get('getCategory_html');//获取分类数据
//        if($res_html == null){
            //如果获取到的数据是空，就从数据库读取数据写入redis
            $cate = \frontend\models\GoodsCategory::findAll(['parent_id'=>0]);;
            $cate_html = $this->renderFile('@app/widgets/view/categories.php', ['cate' => $cate]);
//
           //写入redis
//            $redis->set('getCategory_html',$cate_html);
//        }
        return $cate_html;
    }

}