<?php
/**
 * Created by PhpStorm.
 * User: TT
 * Date: 2017/6/25
 * Time: 9:09
 */

namespace frontend\widgets;

use yii\bootstrap\Widget;

class Upnav extends Widget{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

    }

    public function run()
    {
        $user = \Yii::$app->user;

        return $this->renderFile('@app/widgets/view/nav.php',['user'=>$user]);

    }
}